export const CHORD_DATA = {
  "C major":  { notes: ["C4","E4","G4"],    next: [{ chord: "Am7",   notes: ["A3","C4","E4","G4"], label: "Familiar" }, { chord: "Fmaj7", notes: ["F3","A3","C4","E4"], label: "Opens out" }, { chord: "G",     notes: ["G3","B3","D4"], label: "Moves forward" }] },
  "C minor":  { notes: ["C4","Eb4","G4"],   next: [{ chord: "Ab",    notes: ["Ab3","C4","Eb4"], label: "Opens out" }, { chord: "Eb",    notes: ["Eb3","G3","Bb3"], label: "Lift" }, { chord: "G7",    notes: ["G3","B3","D4","F4"], label: "Tension" }] },
  "C7":       { notes: ["C4","E4","G4","Bb4"], next: [{ chord: "F",  notes: ["F3","A3","C4"], label: "Tension" }, { chord: "Fm",    notes: ["F3","Ab3","C4"], label: "Darker" }, { chord: "Am",    notes: ["A3","C4","E4"], label: "Familiar" }] },
  "Cmaj7":    { notes: ["C4","E4","G4","B4"],  next: [{ chord: "Am7",notes: ["A3","C4","E4","G4"], label: "Familiar" }, { chord: "Fmaj7",notes: ["F3","A3","C4","E4"], label: "Opens out" }, { chord: "Dm7",  notes: ["D4","F4","A4","C5"], label: "Moves forward" }] },
  "Cm7":      { notes: ["C4","Eb4","G4","Bb4"],next: [{ chord: "Fm7",notes: ["F3","Ab3","C4","Eb4"], label: "Darker" }, { chord: "Abmaj7",notes: ["Ab3","C4","Eb4","G4"], label: "Opens out" }, { chord: "Ebmaj7",notes: ["Eb3","G3","Bb3","D4"], label: "Familiar" }] },
  "Cadd9":    { notes: ["C4","E4","G4","D5"],  next: [{ chord: "G",  notes: ["G3","B3","D4"], label: "Opens out" }, { chord: "Am",    notes: ["A3","C4","E4"], label: "Familiar" }, { chord: "Fmaj7",notes: ["F3","A3","C4","E4"], label: "Lift" }] },
  "Csus4":    { notes: ["C4","F4","G4"],        next: [{ chord: "C",  notes: ["C4","E4","G4"], label: "Resolution" }, { chord: "Am",    notes: ["A3","C4","E4"], label: "Familiar" }, { chord: "G",     notes: ["G3","B3","D4"], label: "Moves forward" }] },
  "Fmaj7":    { notes: ["F3","A3","C4","E4"],   next: [{ chord: "C",  notes: ["C4","E4","G4"], label: "Familiar" }, { chord: "Am7",   notes: ["A3","C4","E4","G4"], label: "Darker" }, { chord: "Dm7",   notes: ["D4","F4","A4","C5"], label: "Moves forward" }] },
  "G7":       { notes: ["G3","B3","D4","F4"],   next: [{ chord: "C",  notes: ["C4","E4","G4"], label: "Resolution" }, { chord: "Cm",    notes: ["C4","Eb4","G4"], label: "Darker" }, { chord: "Em",    notes: ["E4","G4","B4"], label: "Familiar" }] },
  "Am7":      { notes: ["A3","C4","E4","G4"],   next: [{ chord: "Fmaj7",notes: ["F3","A3","C4","E4"], label: "Familiar" }, { chord: "Dm7",notes: ["D4","F4","A4","C5"], label: "Moves forward" }, { chord: "C",notes: ["C4","E4","G4"], label: "Opens out" }] },
  "Dm7":      { notes: ["D4","F4","A4","C5"],   next: [{ chord: "G7", notes: ["G3","B3","D4","F4"], label: "Tension" }, { chord: "Cmaj7",notes: ["C4","E4","G4","B4"], label: "Resolution" }, { chord: "Am7",notes: ["A3","C4","E4","G4"], label: "Familiar" }] },
  "E7":       { notes: ["E3","G#3","B3","D4"],  next: [{ chord: "Am", notes: ["A3","C4","E4"], label: "Tension" }, { chord: "Am7",   notes: ["A3","C4","E4","G4"], label: "Familiar" }, { chord: "A",     notes: ["A3","C#4","E4"], label: "Darker" }] },

  "D major": { notes: ["D4","F#4","A4"],   next: [{ chord: "Bm",  notes: ["B3","D4","F#4"],   label: "Familiar" }, { chord: "G",  notes: ["G3","B3","D4"],    label: "Opens out" },  { chord: "A",  notes: ["A3","C#4","E4"],   label: "Moves forward" }] },
  "D minor": { notes: ["D4","F4","A4"],    next: [{ chord: "Gm",  notes: ["G3","Bb3","D4"],   label: "Darker"   }, { chord: "Bb", notes: ["Bb3","D4","F4"],   label: "Opens out" },  { chord: "F",  notes: ["F3","A3","C4"],    label: "Familiar"      }] },
  "E major": { notes: ["E4","G#4","B4"],   next: [{ chord: "C#m", notes: ["C#4","E4","G#4"],  label: "Familiar" }, { chord: "A",  notes: ["A3","C#4","E4"],   label: "Opens out" },  { chord: "B",  notes: ["B3","D#4","F#4"],  label: "Moves forward" }] },
  "E minor": { notes: ["E4","G4","B4"],    next: [{ chord: "Am",  notes: ["A3","C4","E4"],    label: "Darker"   }, { chord: "C",  notes: ["C4","E4","G4"],    label: "Opens out" },  { chord: "G",  notes: ["G3","B3","D4"],    label: "Familiar"      }] },
  "F major": { notes: ["F3","A3","C4"],    next: [{ chord: "Dm",  notes: ["D4","F4","A4"],    label: "Familiar" }, { chord: "Bb", notes: ["Bb3","D4","F4"],   label: "Opens out" },  { chord: "C",  notes: ["C4","E4","G4"],    label: "Moves forward" }] },
  "F minor": { notes: ["F3","Ab3","C4"],   next: [{ chord: "Bbm", notes: ["Bb3","Db4","F4"],  label: "Darker"   }, { chord: "Db", notes: ["Db4","F4","Ab4"],  label: "Opens out" },  { chord: "Ab", notes: ["Ab3","C4","Eb4"],  label: "Familiar"      }] },
  "G major": { notes: ["G3","B3","D4"],    next: [{ chord: "Em",  notes: ["E4","G4","B4"],    label: "Familiar" }, { chord: "C",  notes: ["C4","E4","G4"],    label: "Opens out" },  { chord: "D",  notes: ["D4","F#4","A4"],   label: "Moves forward" }] },
  "G minor": { notes: ["G3","Bb3","D4"],   next: [{ chord: "Cm",  notes: ["C4","Eb4","G4"],   label: "Darker"   }, { chord: "Eb", notes: ["Eb3","G3","Bb3"],  label: "Opens out" },  { chord: "Bb", notes: ["Bb3","D4","F4"],   label: "Familiar"      }] },
  "A major": { notes: ["A3","C#4","E4"],   next: [{ chord: "F#m", notes: ["F#3","A3","C#4"],  label: "Familiar" }, { chord: "D",  notes: ["D4","F#4","A4"],   label: "Opens out" },  { chord: "E",  notes: ["E4","G#4","B4"],   label: "Moves forward" }] },
  "A minor": { notes: ["A3","C4","E4"],    next: [{ chord: "Dm",  notes: ["D4","F4","A4"],    label: "Darker"   }, { chord: "F",  notes: ["F3","A3","C4"],    label: "Opens out" },  { chord: "C",  notes: ["C4","E4","G4"],    label: "Familiar"      }] },
  "B major": { notes: ["B3","D#4","F#4"],  next: [{ chord: "G#m", notes: ["G#3","B3","D#4"],  label: "Familiar" }, { chord: "E",  notes: ["E4","G#4","B4"],   label: "Opens out" },  { chord: "F#", notes: ["F#3","A#3","C#4"], label: "Moves forward" }] },
  "B minor": { notes: ["B3","D4","F#4"],   next: [{ chord: "Em",  notes: ["E4","G4","B4"],    label: "Darker"   }, { chord: "G",  notes: ["G3","B3","D4"],    label: "Opens out" },  { chord: "D",  notes: ["D4","F#4","A4"],   label: "Familiar"      }] },

  // Phase 1.6 — full chord dataset: 7, maj7, m7, add9, sus2, sus4 across all 7 natural roots
  "Csus2": { notes: ["C4","D4","G4"], next: [{ chord: "C", notes: ["C4","E4","G4"], label: "Resolution" }, { chord: "G", notes: ["G3","B3","D4"], label: "Moves forward" }, { chord: "Am", notes: ["A3","C4","E4"], label: "Familiar" }] },
  "D7": { notes: ["D4","F#4","A4","C5"], next: [{ chord: "G", notes: ["G3","B3","D4"], label: "Resolution" }, { chord: "Gm", notes: ["G3","Bb3","D4"], label: "Darker" }, { chord: "Bm", notes: ["B3","D4","F#4"], label: "Familiar" }] },
  "Dmaj7": { notes: ["D4","F#4","A4","C#5"], next: [{ chord: "Bm7", notes: ["B3","D4","F#4","A4"], label: "Familiar" }, { chord: "Gmaj7", notes: ["G3","B3","D4","F#4"], label: "Opens out" }, { chord: "Em7", notes: ["E4","G4","B4","D5"], label: "Moves forward" }] },
  "Dadd9": { notes: ["D3","F#3","A3","E4"], next: [{ chord: "A", notes: ["A3","C#4","E4"], label: "Opens out" }, { chord: "Bm", notes: ["B3","D4","F#4"], label: "Familiar" }, { chord: "Gmaj7", notes: ["G3","B3","D4","F#4"], label: "Lift" }] },
  "Dsus2": { notes: ["D4","E4","A4"], next: [{ chord: "D", notes: ["D4","F#4","A4"], label: "Resolution" }, { chord: "A", notes: ["A3","C#4","E4"], label: "Moves forward" }, { chord: "Bm", notes: ["B3","D4","F#4"], label: "Familiar" }] },
  "Dsus4": { notes: ["D4","G4","A4"], next: [{ chord: "D", notes: ["D4","F#4","A4"], label: "Resolution" }, { chord: "Bm", notes: ["B3","D4","F#4"], label: "Familiar" }, { chord: "A", notes: ["A3","C#4","E4"], label: "Moves forward" }] },
  "Emaj7": { notes: ["E3","G#3","B3","D#4"], next: [{ chord: "C#m7", notes: ["C#4","E4","G#4","B4"], label: "Familiar" }, { chord: "Amaj7", notes: ["A3","C#4","E4","G#4"], label: "Opens out" }, { chord: "F#m7", notes: ["F#3","A3","C#4","E4"], label: "Moves forward" }] },
  "Em7": { notes: ["E4","G4","B4","D5"], next: [{ chord: "Am7", notes: ["A3","C4","E4","G4"], label: "Darker" }, { chord: "Cmaj7", notes: ["C4","E4","G4","B4"], label: "Opens out" }, { chord: "Gmaj7", notes: ["G3","B3","D4","F#4"], label: "Familiar" }] },
  "Eadd9": { notes: ["E3","G#3","B3","F#4"], next: [{ chord: "B", notes: ["B3","D#4","F#4"], label: "Opens out" }, { chord: "C#m", notes: ["C#4","E4","G#4"], label: "Familiar" }, { chord: "Amaj7", notes: ["A3","C#4","E4","G#4"], label: "Lift" }] },
  "Esus2": { notes: ["E4","F#4","B4"], next: [{ chord: "E", notes: ["E4","G#4","B4"], label: "Resolution" }, { chord: "B", notes: ["B3","D#4","F#4"], label: "Moves forward" }, { chord: "C#m", notes: ["C#4","E4","G#4"], label: "Familiar" }] },
  "Esus4": { notes: ["E4","A4","B4"], next: [{ chord: "E", notes: ["E4","G#4","B4"], label: "Resolution" }, { chord: "C#m", notes: ["C#4","E4","G#4"], label: "Familiar" }, { chord: "B", notes: ["B3","D#4","F#4"], label: "Moves forward" }] },
  "F7": { notes: ["F3","A3","C4","Eb4"], next: [{ chord: "Bb", notes: ["Bb3","D4","F4"], label: "Resolution" }, { chord: "Bbm", notes: ["Bb3","Db4","F4"], label: "Darker" }, { chord: "Dm", notes: ["D4","F4","A4"], label: "Familiar" }] },
  "Fm7": { notes: ["F3","Ab3","C4","Eb4"], next: [{ chord: "Bbm7", notes: ["Bb3","Db4","F4","Ab4"], label: "Darker" }, { chord: "Dbmaj7", notes: ["Db4","F4","Ab4","C5"], label: "Opens out" }, { chord: "Abmaj7", notes: ["Ab3","C4","Eb4","G4"], label: "Familiar" }] },
  "Fadd9": { notes: ["F3","A3","C4","G4"], next: [{ chord: "C", notes: ["C4","E4","G4"], label: "Opens out" }, { chord: "Dm", notes: ["D4","F4","A4"], label: "Familiar" }, { chord: "Bbmaj7", notes: ["Bb3","D4","F4","A4"], label: "Lift" }] },
  "Fsus2": { notes: ["F3","G3","C4"], next: [{ chord: "F", notes: ["F3","A3","C4"], label: "Resolution" }, { chord: "C", notes: ["C4","E4","G4"], label: "Moves forward" }, { chord: "Dm", notes: ["D4","F4","A4"], label: "Familiar" }] },
  "Fsus4": { notes: ["F3","Bb3","C4"], next: [{ chord: "F", notes: ["F3","A3","C4"], label: "Resolution" }, { chord: "Dm", notes: ["D4","F4","A4"], label: "Familiar" }, { chord: "C", notes: ["C4","E4","G4"], label: "Moves forward" }] },
  "Gmaj7": { notes: ["G3","B3","D4","F#4"], next: [{ chord: "Em7", notes: ["E4","G4","B4","D5"], label: "Familiar" }, { chord: "Cmaj7", notes: ["C4","E4","G4","B4"], label: "Opens out" }, { chord: "Am7", notes: ["A3","C4","E4","G4"], label: "Moves forward" }] },
  "Gm7": { notes: ["G3","Bb3","D4","F4"], next: [{ chord: "Cm7", notes: ["C4","Eb4","G4","Bb4"], label: "Darker" }, { chord: "Ebmaj7", notes: ["Eb4","G4","Bb4","D5"], label: "Opens out" }, { chord: "Bbmaj7", notes: ["Bb3","D4","F4","A4"], label: "Familiar" }] },
  "Gadd9": { notes: ["G3","B3","D4","A4"], next: [{ chord: "D", notes: ["D4","F#4","A4"], label: "Opens out" }, { chord: "Em", notes: ["E4","G4","B4"], label: "Familiar" }, { chord: "Cmaj7", notes: ["C4","E4","G4","B4"], label: "Lift" }] },
  "Gsus2": { notes: ["G3","A3","D4"], next: [{ chord: "G", notes: ["G3","B3","D4"], label: "Resolution" }, { chord: "D", notes: ["D4","F#4","A4"], label: "Moves forward" }, { chord: "Em", notes: ["E4","G4","B4"], label: "Familiar" }] },
  "Gsus4": { notes: ["G3","C4","D4"], next: [{ chord: "G", notes: ["G3","B3","D4"], label: "Resolution" }, { chord: "Em", notes: ["E4","G4","B4"], label: "Familiar" }, { chord: "D", notes: ["D4","F#4","A4"], label: "Moves forward" }] },
  "A7": { notes: ["A3","C#4","E4","G4"], next: [{ chord: "D", notes: ["D4","F#4","A4"], label: "Resolution" }, { chord: "Dm", notes: ["D4","F4","A4"], label: "Darker" }, { chord: "F#m", notes: ["F#4","A4","C#5"], label: "Familiar" }] },
  "Amaj7": { notes: ["A3","C#4","E4","G#4"], next: [{ chord: "F#m7", notes: ["F#3","A3","C#4","E4"], label: "Familiar" }, { chord: "Dmaj7", notes: ["D4","F#4","A4","C#5"], label: "Opens out" }, { chord: "Bm7", notes: ["B3","D4","F#4","A4"], label: "Moves forward" }] },
  "Aadd9": { notes: ["A3","C#4","E4","B4"], next: [{ chord: "E", notes: ["E4","G#4","B4"], label: "Opens out" }, { chord: "F#m", notes: ["F#4","A4","C#5"], label: "Familiar" }, { chord: "Dmaj7", notes: ["D4","F#4","A4","C#5"], label: "Lift" }] },
  "Asus2": { notes: ["A3","B3","E4"], next: [{ chord: "A", notes: ["A3","C#4","E4"], label: "Resolution" }, { chord: "E", notes: ["E4","G#4","B4"], label: "Moves forward" }, { chord: "F#m", notes: ["F#4","A4","C#5"], label: "Familiar" }] },
  "Asus4": { notes: ["A3","D4","E4"], next: [{ chord: "A", notes: ["A3","C#4","E4"], label: "Resolution" }, { chord: "F#m", notes: ["F#4","A4","C#5"], label: "Familiar" }, { chord: "E", notes: ["E4","G#4","B4"], label: "Moves forward" }] },
  "B7": { notes: ["B3","D#4","F#4","A4"], next: [{ chord: "E", notes: ["E4","G#4","B4"], label: "Resolution" }, { chord: "Em", notes: ["E4","G4","B4"], label: "Darker" }, { chord: "G#m", notes: ["G#3","B3","D#4"], label: "Familiar" }] },
  "Bmaj7": { notes: ["B3","D#4","F#4","A#4"], next: [{ chord: "G#m7", notes: ["G#3","B3","D#4","F#4"], label: "Familiar" }, { chord: "Emaj7", notes: ["E3","G#3","B3","D#4"], label: "Opens out" }, { chord: "C#m7", notes: ["C#4","E4","G#4","B4"], label: "Moves forward" }] },
  "Bm7": { notes: ["B3","D4","F#4","A4"], next: [{ chord: "Em7", notes: ["E4","G4","B4","D5"], label: "Darker" }, { chord: "Gmaj7", notes: ["G3","B3","D4","F#4"], label: "Opens out" }, { chord: "Dmaj7", notes: ["D4","F#4","A4","C#5"], label: "Familiar" }] },
  "Badd9": { notes: ["B3","D#4","F#4","C#5"], next: [{ chord: "F#", notes: ["F#4","A#4","C#5"], label: "Opens out" }, { chord: "G#m", notes: ["G#3","B3","D#4"], label: "Familiar" }, { chord: "Emaj7", notes: ["E3","G#3","B3","D#4"], label: "Lift" }] },
  "Bsus2": { notes: ["B3","C#4","F#4"], next: [{ chord: "B", notes: ["B3","D#4","F#4"], label: "Resolution" }, { chord: "F#", notes: ["F#4","A#4","C#5"], label: "Moves forward" }, { chord: "G#m", notes: ["G#3","B3","D#4"], label: "Familiar" }] },
  "Bsus4": { notes: ["B3","E4","F#4"], next: [{ chord: "B", notes: ["B3","D#4","F#4"], label: "Resolution" }, { chord: "G#m", notes: ["G#3","B3","D#4"], label: "Familiar" }, { chord: "F#", notes: ["F#4","A#4","C#5"], label: "Moves forward" }] }
};

export const LABEL_COLORS = {
  "Familiar":       { bg: "#e8f5f5", text: "#117a79" },
  "Opens out":      { bg: "#e8f0fb", text: "#2a5fc9" },
  "Moves forward":  { bg: "#fff3e0", text: "#c26f00" },
  "Tension":        { bg: "#fde8e8", text: "#c0392b" },
  "Darker":         { bg: "#ede8f5", text: "#5b3fa0" },
  "Lift":           { bg: "#e8f5eb", text: "#1a7a3a" },
  "Surprise":       { bg: "#fde8f5", text: "#a0284a" },
  "Resolution":     { bg: "#f0ffe8", text: "#2d7a1a" },
};

export const LABEL_COLORS_DARK = {
  "Familiar":       { bg: "#123433", text: "#5fd1cb" },
  "Opens out":      { bg: "#16233d", text: "#7ea6f5" },
  "Moves forward":  { bg: "#3a2a0f", text: "#f0aa4d" },
  "Tension":        { bg: "#3a1616", text: "#f0817a" },
  "Darker":         { bg: "#241c38", text: "#b79ae8" },
  "Lift":           { bg: "#16321f", text: "#6fd98c" },
  "Surprise":       { bg: "#3a1626", text: "#f080a8" },
  "Resolution":     { bg: "#243a13", text: "#9ad96f" },
};

export const LABEL_EXPLANATIONS = {
  "Familiar":       "A natural next step that stays close to home — an easy, expected move.",
  "Opens out":      "Steps outside the immediate key, widening the harmonic colour.",
  "Moves forward":  "Pushes the progression toward a new centre, creating a sense of motion.",
  "Tension":        "Builds tension that wants to resolve, adding a pull forward.",
  "Darker":         "Shifts to a minor colour, giving the progression a more introspective feel.",
  "Lift":           "Brightens the mood, lifting the energy of the progression.",
  "Surprise":       "An unexpected turn that breaks from the obvious choice.",
  "Resolution":     "Resolves the tension and feels like coming home.",
};
